# Generated by Django 3.2.7 on 2021-10-01 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.CharField(default='2abd3b70412f', max_length=12, unique=True, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('position_lat', models.FloatField(default=0.0)),
                ('position_lng', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.CharField(default='f6bac622', max_length=8, unique=True, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0, max_length=8)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.CharField(default='050feee41780483a8712b9ee66080f2d', max_length=16, unique=True, verbose_name='ID')),
                ('start_position_lat', models.FloatField(default=0.0)),
                ('start_position_lng', models.FloatField(default=0.0)),
                ('finish_position_lat', models.FloatField(blank=True, default=0.0, null=True)),
                ('finish_position_lng', models.FloatField(blank=True, default=0.0, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.bike')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.CharField(default='5772ccbaef914e9d9df97d72644c78cc', max_length=16, unique=True, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.bike')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.customer')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
